
# Permalinks
permalink:        pretty


# Setup
title:            I Dream in SQL
tagline:          ''
description:      ''
url:              
baseurl:          /

author:
  name:           'Matthew Carter'
  url:            

paginate:         5
